### ISSUE TITLE
Implementation: Configure InfluxDB

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#11]
- Set up database.
- Test (concurrent) R/W operations.
- Any other tasks deemed appropriate.

**Comment by Yapping72** [comment]
- InfluxDB hosted in Google Cloud. Have a working container in Raspberry Pi as well.
- Concurrent Writes tested.
- Reading from Db some slight bugs, if reads are too large server crashes e.g., read past 30days, 1s window. May not need since using Grafana for reading.
- Exploring Grafana for Sprint 2.
