### ISSUE TITLE
Sprint 2 Retrospective

### ISSUE THREAD

**Issue by chococtea** [danialhbma/ITP-SE12-Power-Monitoring#29]
Based on Sprint 2, each member to reflect on these questions:
1. What went well in the Sprint?
2. What could be improved?
3. What will we commit to improving in the next Sprint?

**Comment by danialhbma** [comment]
**What went well in the Sprint?**
- Hardware installation went well, albeit with some hiccups. Glad we could begin data collection during this Sprint. 
- As usual, everyone managed to keep up their end of the bargain & complete their tasks on time 

**What could be improved?**
- Better task distribution, ensuring everyone has an equal amount of work to do 
- (for me) attend meetings

**What will we commit to improving in the next Sprint?**
- Continue delivering according to the expectations of both our industry and academic supervisors 
- (for me) remember meetings

**Comment by chococtea** [comment]
**What went well in the Sprint?**

- Completed the tasks assigned on time.
- Challenges faced were addressed efficiently by the team.
- Kept up with the weekly meetings/reviews.

**What could be improved?**

- Tasks could be distributed more evenly to ensure a more balanced workload among team members.

**What will we commit to improving in the next Sprint?**

- Distribute the remaining tasks for Sprint 3 & 4 equally.

**Comment by ong-yi-xuan** [comment]
**What went well in the Sprint?**
- team came together to quickly figure out and resolve any technical issues faced
- everyone completed their tasks on time and well
- weekly meetings for regular check-ins and updates
- project board updated regularly and clearly

**What could be improved?**
- equal workload distribution among team

**What will we commit to improving in the next Sprint?**
- distribute workload more evenly

**Comment by yucan-yu** [comment]
**What went well in the Sprint?**
- Effective Sprint Planning and breakdown of tasks compared to Sprint 1.
- Sprint Goal met with complete installation and data visualisation.
- Improved coding practices to ensure maintainability and reusability (y'all are welcome); team has minimal worries shall client decide to request implementation of more sensors, etc.
- Better playing to each member's strength, e.g. HOTO of sensor, database backups, etc.

**What could be improved?**
- Members to take more initiative in delegating/taking on work to achieve a fairer workload distribution; talk is easy.
- Lack of considerations in a few aspects of testing.
- Updating stakeholders on progress as team may forget at times. 

**What will we commit to improving in the next Sprint?**
- Collaboration can still be improved - to throw away any mindset that we are only responsible for our individual tasks.
- More attention to detail during software testing phases, especially during calibration and coming up with various possible scenarios.
- Update stakeholders immediately whenever necessary and not drag due to whatever reasons.

**Comment by Yapping72** [comment]
**What went well?**

-  Cleared major milestones for the project i.e., installation of working sensors, collecting live data and initial dashboard displaying collected data.
- Added secondary details i.e., database backups and verified that backups can be restored.
- Each member successfully delivered task assigned.

**What could be improved?**

- Increase interaction with prof / client.
- More robust testing, team should have worked together to discuss how system / sensors were tested to ensure that gaps can be covered clearly. 
- Confirm, clarify and document deliverables that client / prof wants.

**What will we commit to improving in the next Sprint?**

- Improve collaboration.
- Start on report and documenetation.
