### ISSUE TITLE
Sprint 1 Retrospective

### ISSUE THREAD

**Issue by ong-yi-xuan** [danialhbma/ITP-SE12-Power-Monitoring#4]
review of sprint 1 based on the following questions:
What went well in the Sprint
What could be improved?
What will we commit to improving in the next Sprint?

**Comment by yucan-yu** [comment]
**What went well in the Sprint?**
- Willingness to work on unfamiliar domains.
- Constant reviews initiated and conducted within members.
- Tasks were generally allocated fairly and completed on time.

**What could be improved?**
- Can be more proactive in updating the project board.
- Follow documentation previously done to avoid unnecesary delays.
- Attention to minor details.

**What will we commit to improving in the next Sprint?**
- A better Sprint Planning to come out with a more precise Sprint Backlog.
- Have a centralised area to store all documentations for easy referral.
- Try to get everyone present in the necessary meetings, so that no one misses out on any important information.

**Comment by Yapping72** [comment]
**What went well in the Sprint?**
- Constant meetings and reviews were conducted.
- Met most of the sprint 1 deadlines.
- Challenges faced were effectively communicated amongst team members.

**What could be improved?**
- Attention to minor details.

**What will we commit to improving in the next Sprint?**
- More in-depth task breakdown once project comes together. 
- Try and get some sensors installed, to determine if system works in a live environment.

**Comment by danialhbma** [comment]
**What went well in the Sprint?**

- Tasks assigned were handled well, each member held up their end of the bargain each week
- Research was performed thoroughly 

**What could be improved?**

- Taking more initiatives to split up tasks and ensure equal workload
- Understanding why we are doing things in specific ways

**What will we commit to improving in the next Sprint?**

- Try to consistently keep everyone in the loop regarding their personal task progress, either through weekly meetings or daily updates
- Keeping up with the project board items, ensuring each task has the necessary comments & updates required

**Comment by chococtea** [comment]
**What went well in the Sprint?**

- Most of the tasks are completed within the deadline.
- Weekly meetings and reviewing of progress were conducted.
- Willingness to attempt different approaches to accomplish the given tasks.

**What could be improved?**

- More consistent updates for the project board.

**What will we commit to improving in the next Sprint?**

- Ensure that the project board reflects our current progress by regularly updating it.

**Comment by ong-yi-xuan** [comment]
**What went well in the Sprint**
- team members were all willing to work with unfamiliar technology and helped each other with understanding them
- everyone contributed to team meetings

**What could be improved?**
- timely decision-making on important choices (e.g. where our services should be hosted) -> led to unnecessary work and time lost setting up and restarting setup repeatedly
- progress updates: team could have done better updating progress board and communicating in group chat about each other's progress
- workload distribution unfairly skewed towards those handling hardware. im dying

**What will we commit to improving in the next Sprint?**
- regular check-ins and progress updates with team
- decide on important choices early
