### ISSUE TITLE
Research: Finalise DB

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ITP-SE12-Power-Monitoring#5]
InfluxDB for now

**Comment by yucan-yu** [comment]
Rationale for using InfluxDB:
1. Optimised for time-series data.
2. Flexible in storing data due to its schema-less structure, suitable for IoT applications.
3. Ability to perform high-speed writes, important for our use cases.
4. Ability to perform concurrent queries.
5. Ability to easily integrate with visualisation tools such as Grafana, etc.
