### ISSUE TITLE
Sprint 3 Retrospective

### ISSUE THREAD

**Issue by yucan-yu** [danialhbma/ITP-SE12-Power-Monitoring#53]
Based on Sprint 3, each member to reflect on these questions:
1. What went well in the Sprint?
2. What could be improved?
3. What will we commit to improving in the next Sprint?

**Comment by danialhbma** [comment]
**What went well in the Sprint?**
- Tasks and features we set out to complete this sprint were all done
- Responsibility and taking ownership of each assigned task on the project board

**What could be improved?**
- Better communication on changes
- Keeping each other updated on task progress 

**What will we commit to improving in the next Sprint?**
- Work on completing the final report & preparing for the final presentation
- Ensuring that every member knows how to justify each decision made, and why they worked on certain things in certain ways (for example, why we chose to monitor external environmental conditions) to make sure the markers are satisfied with our project

**Comment by yucan-yu** [comment]
**What went well in the Sprint?**
- All user stories were met as tasks for this Sprint were mostly completed.
- Members were independent in completing their assigned tasks.

**What could be improved?**
- Mainly transparency issues; there were many instances of members not knowing what one another was up to, even after internal meetings and message updates.
- Motivation could have been higher, although understandable as our ITP project seemed the largest and busiest amongst all teams in SE.
- Respect for one another's roles and deliverables.

**What will we commit to improving in the next Sprint?**
- Ensuring that all ITP objectives (especially the submission deliverables) are met.

**Comment by ong-yi-xuan** [comment]
What went well in the Sprint?
- everyone completed their assigned work this sprint, so we're on good pace

What could be improved?
- report writing mostly untouched until end of sprint despite prompts
- communication: members were all on different pages regarding some issues and didn't know what was going on
- updates on task progression has really fallen short this time despite it being good last sprint, now project board is updated but theres no updates in the team channels

What will we commit to improving in the next Sprint?
- finishing deliverables (report, video, poster)
- neatening repository if there's time since its very messy with multiple duplicate files rn

**Comment by Yapping72** [comment]
What went well in the Sprint?

- Completed assigned task, resolved most bugs.
- Cleared all user stories. 

What could be improved?
- Team communication 

What will we commit to improving in the next sprint?
- Submissions and presentation.

**Comment by chococtea** [comment]
**What went well in the Sprint?**
- Tasks assigned to this sprint were completed on time.
- Each member updated their progress on the project board accordingly.

**What could be improved?**
- There was some miscommunication about certain areas of the project.

**What will we commit to improving in the next Sprint?**
- Work on finishing the remaining deliverables.
-  Start preparing for the presentation and Q&A. (esp me)
