### ISSUE TITLE
Analysis: Monthly Cost Estimation

### ISSUE THREAD

**Issue by chococtea** [danialhbma/ITP-SE12-Power-Monitoring#59]
The monthly cost estimation analysis will be combined with the calculator tool due to changes from the initial monthly cost estimation analysis (Not using linear regression anymore but using statistical means analysis instead).

**Comment by ong-yi-xuan** [comment]
1.dervied the mean watts measured from rack 1 (purple led) and rack 2 (white led) for:

- led on
- led off
- water pump on (based on our collected data + confirmation from crop scientist, the pumps are always on)

2.used unpaired t-test on the means
- all 3 measurements were found to be statistically significant

3.plan:
- led: calculate the power consumption of puple and white led separately (2 means)
- water: since same water pump is used for both racks, even tho the measured data is different we intend to combine their means to calculate power consumption using 1 mean

**Comment by ong-yi-xuan** [comment]
- uses historical mean from Power Consumption.csv ✅
- calculated power consumption of purple and white led both on and off ✅
- calculated power consumption of water pump using combined mean ✅

sample calculations below have the following configurations based on the current farm setup:
- both LEDs are turned on for 12 hours, and turned off for 12 hours
- water pumps are running for 24 hours
- 3 purple LED racks and 6 white LED racks were observed on the farm
- calculated for whole month of July (31 days) - num of days automatically derived for each month

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/656fddd5-f49e-4251-b51d-90cf4403ab09)


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/eaa1ee51-1322-4383-a494-e0aa0611589c)



![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/f48d7ece-dae7-48a2-9823-8303a29a5750)

wip: aircon calculation

**Comment by ong-yi-xuan** [comment]
aircon calculation completed using flat rate
wip: modifying calculator UI and api backend

**Comment by ong-yi-xuan** [comment]
- api completed ✅
    - /rack_calculator endpoint: calculates power consumption for 1 rack based on led colour, number of hours led is on, and number of days ran
    - /container_calculator endpoint; simulates whole container if various conditions were different
- nginx.conf modified to allow access to new endpoints ✅
- code and configurations pushed ✅
- calculator UI completed ✅


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/114a5873-6434-42d2-8f6a-f483da46a10c)

**Comment by ong-yi-xuan** [comment]
- calculator can now display result in same panel instead of via popup ✅
modified rack calculation based on academic supervisor's feedback ✅
- users can now input their own appliance wattage for calculating power consumption with different LED and water pumps (instead of assuming same LED and water pumps are used)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/48bf995e-33ee-4211-b6e8-bfb2c4c41e64)

wip: modifying api backend for container calculator

**Comment by ong-yi-xuan** [comment]
- modified container calculation so users can input wattage of new LED lights, water pumps and aircon ✅
- added cost calculation to rack and container calculators ✅


![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/ebaf2a02-3688-47f0-bf15-c7c8cb7c92bd)

![Image](https://github.com/danialhbma/ITP-SE12-Power-Monitoring/assets/91550661/ef5ddb2a-09f1-4b32-b09d-11da2caf2aea)
